const mongoose = require('mongoose');

const SentJobSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  title: {
    type: String,
    required: [true, 'Please enter a job title'],
    trim: true
  },
  company: {
    type: String,
    required: [true, 'Please enter a company name'],
    trim: true
  },
  location: {
    type: String,
    default: 'Remote',
    trim: true
  },
  applyLink: {
    type: String,
    required: [true, 'Please enter an application link'],
    trim: true
  },
  isDirectLink: {
    type: Boolean,
    default: false
  },
  score: {
    type: Number,
    required: [true, 'Please enter a match score'],
    min: 0,
    max: 100
  },
  reason: {
    type: String,
    default: ''
  },
  matchedSkills: {
    type: [String],
    default: []
  },
  missingSkills: {
    type: [String],
    default: []
  },
  // Store the tailored resume contents generated by the AI for this specific job
  tailoredProfile: {
    bio: { type: String, default: '' },
    experience: [{
      company: { type: String, required: true },
      position: { type: String, required: true },
      description: { type: String, default: '' }
    }],
    projects: [{
      title: { type: String, required: true },
      description: { type: String, default: '' }
    }]
  },
  status: {
    type: String,
    enum: ['matched', 'applied', 'rejected'],
    default: 'matched'
  },
  createdAt: {
    type: Date,
    default: Date.now,
    index: true
  }
});

module.exports = mongoose.model('SentJob', SentJobSchema);
